services:
  postgres:
    image: postgres:17.2
    ports:
      - 5432:5432
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=sandbox
      - POSTGRES_PASSWORD=guest
      - POSTGRES_USER=guest